# -*- coding: utf-8 -*-
"""NLP_project_org.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wi2xaVeHkSzRNJ8P7Sd77osMDnk9PZoZ

## Topic name : Sentiment Analysis and Sector-Based Auto Reply System using NLP
"""

import pandas as pd
import nltk
import string
import matplotlib.pyplot as plt
from wordcloud import WordCloud

from nltk.corpus import stopwords, wordnet
from nltk.stem import WordNetLemmatizer

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# ---------------- DOWNLOAD ---------------- #
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

# ---------------- LOAD DATA ---------------- #
df = pd.read_csv("advanced_nlp_dataset.csv")

# Load keyword CSV
keywords_df = pd.read_csv("expanded_sector_keywords.csv")

# Convert keywords into dictionary
sector_dict = {}
for sector in keywords_df['Sector'].unique():
    sector_dict[sector] = list(
        keywords_df[keywords_df['Sector'] == sector]['Keyword']
    )

# ---------------- PREPROCESSING ---------------- #
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def get_synonyms(word):
    synonyms = set()
    for syn in wordnet.synsets(word):
        for lemma in syn.lemmas():
            synonyms.add(lemma.name())
    return list(synonyms)[:2]

def preprocess(text):
    text = text.lower()
    text = "".join([ch for ch in text if ch not in string.punctuation])

    words = text.split()
    cleaned_words = []

    for word in words:
        if word not in stop_words:
            lemma = lemmatizer.lemmatize(word)
            cleaned_words.append(lemma)
            cleaned_words.extend(get_synonyms(lemma))

    return " ".join(cleaned_words)

df["Clean_Text"] = df["Text"].apply(preprocess)

# ---------------- FEATURE EXTRACTION ---------------- #
vectorizer = TfidfVectorizer(ngram_range=(1,2), max_features=6000)
X = vectorizer.fit_transform(df["Clean_Text"])
y = df["Sentiment"]

# ---------------- MODEL ---------------- #
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model = LogisticRegression(max_iter=400)
model.fit(X_train, y_train)

print("\nModel Accuracy:", accuracy_score(y_test, model.predict(X_test)))

# ---------------- SECTOR DETECTION ---------------- #
def detect_sector(text):
    clean = preprocess(text)

    sector_scores = {}

    for sector, keywords in sector_dict.items():
        count = sum(1 for keyword in keywords if keyword in clean)
        sector_scores[sector] = count

    # Print scores (for debugging)
    print("Sector Scores:", sector_scores)

    # Get sector with highest score
    best_sector = max(sector_scores, key=sector_scores.get)

    if sector_scores[best_sector] == 0:
        return "Unknown"

    return best_sector
# ---------------- AUTO REPLY ---------------- #
def auto_reply(sentiment):
    if sentiment == "Positive":
        return "Thank you for your positive feedback! 😊"
    elif sentiment == "Negative":
        return "We are sorry for your experience 😔"
    else:
        return "Thank you for your feedback."

# ---------------- STORAGE ---------------- #
user_sentiments = []
user_sectors = []
user_texts = []

# ---------------- PREDICTION ---------------- #
def predict(text):
    clean = preprocess(text)
    vector = vectorizer.transform([clean])

    pred = model.predict(vector)[0]
    probs = model.predict_proba(vector)[0]

    sector = detect_sector(text)

    user_sentiments.append(pred)
    user_sectors.append(sector)
    user_texts.append(text)

    print("\n Input:", text)
    print(" Sector:", sector)
    print(" Sentiment:", pred)

    print("\n Probabilities:")
    for label, prob in zip(model.classes_, probs):
        print(f"{label}: {round(prob, 3)}")

    print(" Reply:", auto_reply(pred))

# ---------------- LOOP ---------------- #
while True:
    text = input("\nEnter review (type 'exit'): ")

    if text.lower() == "exit":
        break

    predict(text)

# ---------------- PIE CHART ---------------- #
if len(user_sentiments) > 0:
    sentiment_counts = pd.Series(user_sentiments).value_counts()

    plt.figure()
    plt.pie(sentiment_counts, labels=sentiment_counts.index, autopct='%1.1f%%')
    plt.title("Sentiment Distribution")
    plt.show()

print("\n" + "="*60)
print("Generating WordClouds for Each Sector...")
print("="*60 + "\n")

import time
time.sleep(2)   # small pause for better visualization


# ---------------- WORD CLOUD ---------------- #
df_user = pd.DataFrame({
    "Text": user_texts,
    "Sector": user_sectors
})

for sector in sector_dict.keys():
    text_data = " ".join(df_user[df_user["Sector"] == sector]["Text"])

    if text_data.strip() != "":
        wc = WordCloud().generate(text_data)

        plt.figure()
        plt.imshow(wc)
        plt.axis("off")
        plt.title(f"{sector} WordCloud")
        plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud

# Load dataset (can use your main dataset OR user input file)
df = pd.read_csv("advanced_nlp_dataset.csv")

# Merge all text into one
all_text = " ".join(df["Text"].astype(str))

# Generate WordCloud
wc = WordCloud(
    width=800,
    height=400,
    background_color='white'
).generate(all_text)

# Display WordCloud
plt.figure()
plt.imshow(wc)
plt.axis("off")
plt.title("Combined WordCloud (All Sectors)")
plt.show()

